# Generated by Django 4.2.5 on 2025-03-17 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_options_alter_lesson_video_subscription'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, help_text='Ввелите номер телефона', max_length=35, null=True, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата платежа')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость покупки')),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('non_cash', 'non_cash')], default='cash', verbose_name='Способ оплаты')),
                ('session_id', models.CharField(blank=True, help_text='Укажите id сессии', max_length=255, null=True, verbose_name='Id сессии')),
                ('link', models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('payment_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс')),
                ('payment_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто произвел оплату')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
